-- Create Database
CREATE DATABASE employee;
USE employee;

-- Employee Table
CREATE TABLE emp_record_table(
EMP_ID VARCHAR (10) PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR (50),
GENDER VARCHAR (10),
ROLE VARCHAR (50),
DEPT VARCHAR (50),
EXP int,
COUNTRY VARCHAR (50),
CONTINENT varchar (50),
SALARY INT,
EMP_RATING INT,
MANAGER_ID VARCHAR(10),
PROJ_ID VARCHAR(10));

-- Project Table
CREATE TABLE Proj_table(
PROJECT_ID VARCHAR(10)PRIMARY KEY,
PROJ_NAME VARCHAR (100),
DOMAIN VARCHAR (50),
START_DATE VARCHAR (20),
CLOSURE_DATE VARCHAR (20),
DEV_QTR VARCHAR(10),
STATUS VARCHAR (20));

-- Data Science Team Table
CREATE TABLE Data_science_team(
EMP_ID VARCHAR(10) PRIMARY KEY,
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
GENDER VARCHAR(10),
ROLE VARCHAR (50),
DEPT VARCHAR (50),
EXP INT,
COUNTRY VARCHAR(50),
CONTINENT VARCHAR (50));
